#!/bin/sh
TGZ_DEST="$HOME/sites/practical-scheme.net/vault/"
MAN_DEST="$HOME/sties/practical-scheme.net/gauche/man/"
CHANGELOG_DEST="$HOME/sites/practical-scheme.net/gauche/ChangeLog.Gauche-gl.txt"

while [ $# -gt 0 ]; do
  case $1 in
    tgz) tgz=yes; shift ;;
    gen) gen=yes; shift ;;
    *) echo "DIST [tgz]"; exit 0;;
  esac
done

if [ "$gen" = "yes" ]; then
  # we no longer need to run autoconf
  :
fi

if [ "$tgz" = "yes" ]; then
  if [ -f Makefile ]; then make maintainer-clean; fi
  ./configure
  (cd doc; make html)
  make distclean
  gosh doc/extract -en -o INSTALL INSTALL.in
  gosh doc/extract -jp -o INSTALL.utf-8 INSTALL.in

  if [ ! -f VERSION ]; then echo "No VERSION; something wrong?"; exit 1; fi
  VERSION=`cat VERSION`

  rm -f DIST_EXCLUDE_X
  cat DIST_EXCLUDE > DIST_EXCLUDE_X
  find . -name CVS -o -name .svn -print -prune >> DIST_EXCLUDE_X

  rm -rf ../Gauche-gl-$VERSION

  mkdir ../Gauche-gl-$VERSION
  tar cvfX - DIST_EXCLUDE_X . | (cd ../Gauche-gl-$VERSION; tar xf -)
  (cd ..; tar cvf - Gauche-gl-$VERSION | gzip -9 > Gauche-gl-$VERSION.tgz)
#  mv ../Gauche-gl-$VERSION.tgz $TGZ_DEST
  cp ChangeLog $CHANGELOG_DEST
fi

