#!/bin/sh
VERSION=`cat VERSION`
TGZ_DEST="$HOME/shiro.dreamhost.com/scheme/vault/"
MAN_DEST="$HOME/shiro.dreamhost.com/scheme/gauche/man/"

while [ $# -gt 0 ]; do
  case $1 in
    doc) docs=yes; shift ;;
    tgz) tgz=yes; shift ;;
    test) test=yes; shift ;;
    testclean) testclean=yes; shift ;;
    *) echo "DIST [doc][tgz][test][testclean]"; exit 0;;
  esac
done

if [ "$tgz" = "yes" ]; then
  rm -f DIST_EXCLUDE_X
  cat DIST_EXCLUDE > DIST_EXCLUDE_X
  (cd ..; find Gauche-gl -name CVS -print -prune) >> DIST_EXCLUDE_X

  if [ -f Makefile ]; then make realclean; fi
  autoconf -l `gauche-config --ac`
  ./configure
#  (cd doc; make html)
  make distclean
  escm -o INSTALL INSTALL.esc
  LANG=ja_JP escm -o INSTALL.eucjp INSTALL.esc
  (cd ..; tar c -v -f - -X Gauche-gl/DIST_EXCLUDE_X Gauche-gl | gzip -9 > Gauche-gl-$VERSION.tgz)
  mv ../Gauche-gl-$VERSION.tgz $TGZ_DEST
#  cp ChangeLog $CHANGELOG_DEST
fi

