#!/bin/sh
TGZ_DEST="$HOME/shiro.dreamhost.com/scheme/vault/"
MAN_DEST="$HOME/shiro.dreamhost.com/scheme/gauche/man/"
CHANGELOG_DEST="$HOME/shiro.dreamhost.com/scheme/gauche/ChangeLog.Gauche-gl.txt"

while [ $# -gt 0 ]; do
  case $1 in
    doc) docs=yes; shift ;;
    tgz) tgz=yes; shift ;;
    test) test=yes; shift ;;
    testclean) testclean=yes; shift ;;
    *) echo "DIST [doc][tgz][test][testclean]"; exit 0;;
  esac
done

if [ "$tgz" = "yes" ]; then
  if [ -f Makefile ]; then make maintainer-clean; fi
  autoconf -I `gauche-config --ac`
  ./configure
  (cd doc; make html)
  make distclean
  gosh doc/extract -en -o INSTALL INSTALL.in
  gosh doc/extract -jp -o INSTALL.eucjp INSTALL.in

  if [ ! -f VERSION ]; then echo "No VERSION; something wrong?"; exit 1; fi
  VERSION=`cat VERSION`

  rm -f DIST_EXCLUDE_X
  cat DIST_EXCLUDE > DIST_EXCLUDE_X
  find . -name CVS -print -prune >> DIST_EXCLUDE_X

  rm -rf ../Gauche-gl-$VERSION

  mkdir ../Gauche-gl-$VERSION
  tar cvfX - DIST_EXCLUDE_X . | (cd ../Gauche-gl-$VERSION; tar xf -)
  (cd ..; tar cvf - Gauche-gl-$VERSION | gzip -9 > Gauche-gl-$VERSION.tgz)
#  mv ../Gauche-gl-$VERSION.tgz $TGZ_DEST
  cp ChangeLog $CHANGELOG_DEST
fi

