;;;
;;; vulkan-lib.scm - vulkan binding
;;;
;;;  Copyright (c) 2020-2023  Shiro Kawai  <shiro@acm.org>
;;;
;;;  Redistribution and use in source and binary forms, with or without
;;;  modification, are permitted provided that the following conditions
;;;  are met:
;;;
;;;   1. Redistributions of source code must retain the above copyright
;;;      notice, this list of conditions and the following disclaimer.
;;;
;;;   2. Redistributions in binary form must reproduce the above copyright
;;;      notice, this list of conditions and the following disclaimer in the
;;;      documentation and/or other materials provided with the distribution.
;;;
;;;   3. Neither the name of the authors nor the names of its contributors
;;;      may be used to endorse or promote products derived from this
;;;      software without specific prior written permission.
;;;
;;;  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
;;;  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
;;;  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
;;;  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
;;;  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
;;;  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
;;;  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
;;;  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
;;;  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;;  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;;  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
;;;

(select-module gl.vulkan)

(inline-stub
 (declcode (.include "gauche-vulkan.h"))

 ;; Special hanlding of void* pNext pointer
 (define-type <vk-void*> "void*" "Vulkan void*"
   "SCM_VK_VOID_POINTER_P" "SCM_VK_VOID_POINTER" "Scm_MakeVkVoidPointer")

 (define-cenum <vk-result> "VkResult"
   (VK_SUCCESS
    VK_NOT_READY
    VK_TIMEOUT
    VK_EVENT_SET
    VK_EVENT_RESET
    VK_INCOMPLETE
    VK_ERROR_OUT_OF_HOST_MEMORY
    VK_ERROR_OUT_OF_DEVICE_MEMORY
    VK_ERROR_INITIALIZATION_FAILED
    VK_ERROR_DEVICE_LOST
    VK_ERROR_MEMORY_MAP_FAILED
    VK_ERROR_LAYER_NOT_PRESENT
    VK_ERROR_EXTENSION_NOT_PRESENT
    VK_ERROR_FEATURE_NOT_PRESENT
    VK_ERROR_INCOMPATIBLE_DRIVER
    VK_ERROR_TOO_MANY_OBJECTS
    VK_ERROR_FORMAT_NOT_SUPPORTED
    VK_ERROR_FRAGMENTED_POOL
    VK_ERROR_UNKNOWN

    ;; 1.1
    VK_ERROR_OUT_OF_POOL_MEMORY
    VK_ERROR_INVALID_EXTERNAL_HANDLE
    ;; 1.2
    VK_ERROR_FRAGMENTATION
    VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS

    ;; There are a bunch of error code for the extensions; we need
    ;; some way to cope with different enum supports across platforms.
    ))

 (define-cenum <vk-structure-type> "VkStructureType"
   (VK_STRUCTURE_TYPE_APPLICATION_INFO
    VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO
    VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO
    VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO
    VK_STRUCTURE_TYPE_SUBMIT_INFO
    VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO
    VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE
    VK_STRUCTURE_TYPE_BIND_SPARSE_INFO
    VK_STRUCTURE_TYPE_FENCE_CREATE_INFO
    VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO
    VK_STRUCTURE_TYPE_EVENT_CREATE_INFO
    VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO
    VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO
    VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO
    VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO
    VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO
    VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO
    VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO
    VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO
    VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO
    VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO
    VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET
    VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET
    VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO
    VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO
    VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO
    VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO
    VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER
    VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER
    VK_STRUCTURE_TYPE_MEMORY_BARRIER
    VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO
    VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO
    ;; 1.1
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES
    VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO
    VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES
    VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS
    VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO
    VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO
    VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO
    VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO
    VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO
    VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO
    VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO
    VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES
    VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO
    VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2
    VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2
    VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2
    VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2
    VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2
    VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2
    VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2
    VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2
    VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES
    VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO
    VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO
    VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO
    VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES
    VK_STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES
    VK_STRUCTURE_TYPE_DEVICE_QUEUE_INFO_2
    VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO
    VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO
    VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO
    VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES
    VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES
    VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO
    VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO
    VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES
    VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO
    VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO
    VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO
    VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES
    VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO
    VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO
    VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT
    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETER_FEATURES
    ))

 (define-cenum <vk-system-allocation-scope> "VkSystemAllocationScope"
   (VK_SYSTEM_ALLOCATION_SCOPE_COMMAND
    VK_SYSTEM_ALLOCATION_SCOPE_OBJECT
    VK_SYSTEM_ALLOCATION_SCOPE_CACHE
    VK_SYSTEM_ALLOCATION_SCOPE_DEVICE
    VK_SYSTEM_ALLOCATION_SCOPE_INSTANCE
    ))

 (define-cenum <vk-internal-allocation-type> "VkInternalAllocationType"
   (VK_INTERNAL_ALLOCATION_TYPE_EXECUTABLE
    ))

 (define-cenum <vk-format> "VkFormat"
   (VK_FORMAT_UNDEFINED
    VK_FORMAT_R4G4_UNORM_PACK8
    VK_FORMAT_R4G4B4A4_UNORM_PACK16
    VK_FORMAT_B4G4R4A4_UNORM_PACK16
    VK_FORMAT_R5G6B5_UNORM_PACK16
    VK_FORMAT_B5G6R5_UNORM_PACK16
    VK_FORMAT_R5G5B5A1_UNORM_PACK16
    VK_FORMAT_B5G5R5A1_UNORM_PACK16
    VK_FORMAT_A1R5G5B5_UNORM_PACK16
    VK_FORMAT_R8_UNORM
    VK_FORMAT_R8_SNORM
    VK_FORMAT_R8_USCALED
    VK_FORMAT_R8_SSCALED
    VK_FORMAT_R8_UINT
    VK_FORMAT_R8_SINT
    VK_FORMAT_R8_SRGB
    VK_FORMAT_R8G8_UNORM
    VK_FORMAT_R8G8_SNORM
    VK_FORMAT_R8G8_USCALED
    VK_FORMAT_R8G8_SSCALED
    VK_FORMAT_R8G8_UINT
    VK_FORMAT_R8G8_SINT
    VK_FORMAT_R8G8_SRGB
    VK_FORMAT_R8G8B8_UNORM
    VK_FORMAT_R8G8B8_SNORM
    VK_FORMAT_R8G8B8_USCALED
    VK_FORMAT_R8G8B8_SSCALED
    VK_FORMAT_R8G8B8_UINT
    VK_FORMAT_R8G8B8_SINT
    VK_FORMAT_R8G8B8_SRGB
    VK_FORMAT_B8G8R8_UNORM
    VK_FORMAT_B8G8R8_SNORM
    VK_FORMAT_B8G8R8_USCALED
    VK_FORMAT_B8G8R8_SSCALED
    VK_FORMAT_B8G8R8_UINT
    VK_FORMAT_B8G8R8_SINT
    VK_FORMAT_B8G8R8_SRGB
    VK_FORMAT_R8G8B8A8_UNORM
    VK_FORMAT_R8G8B8A8_SNORM
    VK_FORMAT_R8G8B8A8_USCALED
    VK_FORMAT_R8G8B8A8_SSCALED
    VK_FORMAT_R8G8B8A8_UINT
    VK_FORMAT_R8G8B8A8_SINT
    VK_FORMAT_R8G8B8A8_SRGB
    VK_FORMAT_B8G8R8A8_UNORM
    VK_FORMAT_B8G8R8A8_SNORM
    VK_FORMAT_B8G8R8A8_USCALED
    VK_FORMAT_B8G8R8A8_SSCALED
    VK_FORMAT_B8G8R8A8_UINT
    VK_FORMAT_B8G8R8A8_SINT
    VK_FORMAT_B8G8R8A8_SRGB
    VK_FORMAT_A8B8G8R8_UNORM_PACK32
    VK_FORMAT_A8B8G8R8_SNORM_PACK32
    VK_FORMAT_A8B8G8R8_USCALED_PACK32
    VK_FORMAT_A8B8G8R8_SSCALED_PACK32
    VK_FORMAT_A8B8G8R8_UINT_PACK32
    VK_FORMAT_A8B8G8R8_SINT_PACK32
    VK_FORMAT_A8B8G8R8_SRGB_PACK32
    VK_FORMAT_A2R10G10B10_UNORM_PACK32
    VK_FORMAT_A2R10G10B10_SNORM_PACK32
    VK_FORMAT_A2R10G10B10_USCALED_PACK32
    VK_FORMAT_A2R10G10B10_SSCALED_PACK32
    VK_FORMAT_A2R10G10B10_UINT_PACK32
    VK_FORMAT_A2R10G10B10_SINT_PACK32
    VK_FORMAT_A2B10G10R10_UNORM_PACK32
    VK_FORMAT_A2B10G10R10_SNORM_PACK32
    VK_FORMAT_A2B10G10R10_USCALED_PACK32
    VK_FORMAT_A2B10G10R10_SSCALED_PACK32
    VK_FORMAT_A2B10G10R10_UINT_PACK32
    VK_FORMAT_A2B10G10R10_SINT_PACK32
    VK_FORMAT_R16_UNORM
    VK_FORMAT_R16_SNORM
    VK_FORMAT_R16_USCALED
    VK_FORMAT_R16_SSCALED
    VK_FORMAT_R16_UINT
    VK_FORMAT_R16_SINT
    VK_FORMAT_R16_SFLOAT
    VK_FORMAT_R16G16_UNORM
    VK_FORMAT_R16G16_SNORM
    VK_FORMAT_R16G16_USCALED
    VK_FORMAT_R16G16_SSCALED
    VK_FORMAT_R16G16_UINT
    VK_FORMAT_R16G16_SINT
    VK_FORMAT_R16G16_SFLOAT
    VK_FORMAT_R16G16B16_UNORM
    VK_FORMAT_R16G16B16_SNORM
    VK_FORMAT_R16G16B16_USCALED
    VK_FORMAT_R16G16B16_SSCALED
    VK_FORMAT_R16G16B16_UINT
    VK_FORMAT_R16G16B16_SINT
    VK_FORMAT_R16G16B16_SFLOAT
    VK_FORMAT_R16G16B16A16_UNORM
    VK_FORMAT_R16G16B16A16_SNORM
    VK_FORMAT_R16G16B16A16_USCALED
    VK_FORMAT_R16G16B16A16_SSCALED
    VK_FORMAT_R16G16B16A16_UINT
    VK_FORMAT_R16G16B16A16_SINT
    VK_FORMAT_R16G16B16A16_SFLOAT
    VK_FORMAT_R32_UINT
    VK_FORMAT_R32_SINT
    VK_FORMAT_R32_SFLOAT
    VK_FORMAT_R32G32_UINT
    VK_FORMAT_R32G32_SINT
    VK_FORMAT_R32G32_SFLOAT
    VK_FORMAT_R32G32B32_UINT
    VK_FORMAT_R32G32B32_SINT
    VK_FORMAT_R32G32B32_SFLOAT
    VK_FORMAT_R32G32B32A32_UINT
    VK_FORMAT_R32G32B32A32_SINT
    VK_FORMAT_R32G32B32A32_SFLOAT
    VK_FORMAT_R64_UINT
    VK_FORMAT_R64_SINT
    VK_FORMAT_R64_SFLOAT
    VK_FORMAT_R64G64_UINT
    VK_FORMAT_R64G64_SINT
    VK_FORMAT_R64G64_SFLOAT
    VK_FORMAT_R64G64B64_UINT
    VK_FORMAT_R64G64B64_SINT
    VK_FORMAT_R64G64B64_SFLOAT
    VK_FORMAT_R64G64B64A64_UINT
    VK_FORMAT_R64G64B64A64_SINT
    VK_FORMAT_R64G64B64A64_SFLOAT
    VK_FORMAT_B10G11R11_UFLOAT_PACK32
    VK_FORMAT_E5B9G9R9_UFLOAT_PACK32
    VK_FORMAT_D16_UNORM
    VK_FORMAT_X8_D24_UNORM_PACK32
    VK_FORMAT_D32_SFLOAT
    VK_FORMAT_S8_UINT
    VK_FORMAT_D16_UNORM_S8_UINT
    VK_FORMAT_D24_UNORM_S8_UINT
    VK_FORMAT_D32_SFLOAT_S8_UINT
    VK_FORMAT_BC1_RGB_UNORM_BLOCK
    VK_FORMAT_BC1_RGB_SRGB_BLOCK
    VK_FORMAT_BC1_RGBA_UNORM_BLOCK
    VK_FORMAT_BC1_RGBA_SRGB_BLOCK
    VK_FORMAT_BC2_UNORM_BLOCK
    VK_FORMAT_BC2_SRGB_BLOCK
    VK_FORMAT_BC3_UNORM_BLOCK
    VK_FORMAT_BC3_SRGB_BLOCK
    VK_FORMAT_BC4_UNORM_BLOCK
    VK_FORMAT_BC4_SNORM_BLOCK
    VK_FORMAT_BC5_UNORM_BLOCK
    VK_FORMAT_BC5_SNORM_BLOCK
    VK_FORMAT_BC6H_UFLOAT_BLOCK
    VK_FORMAT_BC6H_SFLOAT_BLOCK
    VK_FORMAT_BC7_UNORM_BLOCK
    VK_FORMAT_BC7_SRGB_BLOCK
    VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK
    VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK
    VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK
    VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK
    VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK
    VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK
    VK_FORMAT_EAC_R11_UNORM_BLOCK
    VK_FORMAT_EAC_R11_SNORM_BLOCK
    VK_FORMAT_EAC_R11G11_UNORM_BLOCK
    VK_FORMAT_EAC_R11G11_SNORM_BLOCK
    VK_FORMAT_ASTC_4x4_UNORM_BLOCK
    VK_FORMAT_ASTC_4x4_SRGB_BLOCK
    VK_FORMAT_ASTC_5x4_UNORM_BLOCK
    VK_FORMAT_ASTC_5x4_SRGB_BLOCK
    VK_FORMAT_ASTC_5x5_UNORM_BLOCK
    VK_FORMAT_ASTC_5x5_SRGB_BLOCK
    VK_FORMAT_ASTC_6x5_UNORM_BLOCK
    VK_FORMAT_ASTC_6x5_SRGB_BLOCK
    VK_FORMAT_ASTC_6x6_UNORM_BLOCK
    VK_FORMAT_ASTC_6x6_SRGB_BLOCK
    VK_FORMAT_ASTC_8x5_UNORM_BLOCK
    VK_FORMAT_ASTC_8x5_SRGB_BLOCK
    VK_FORMAT_ASTC_8x6_UNORM_BLOCK
    VK_FORMAT_ASTC_8x6_SRGB_BLOCK
    VK_FORMAT_ASTC_8x8_UNORM_BLOCK
    VK_FORMAT_ASTC_8x8_SRGB_BLOCK
    VK_FORMAT_ASTC_10x5_UNORM_BLOCK
    VK_FORMAT_ASTC_10x5_SRGB_BLOCK
    VK_FORMAT_ASTC_10x6_UNORM_BLOCK
    VK_FORMAT_ASTC_10x6_SRGB_BLOCK
    VK_FORMAT_ASTC_10x8_UNORM_BLOCK
    VK_FORMAT_ASTC_10x8_SRGB_BLOCK
    VK_FORMAT_ASTC_10x10_UNORM_BLOCK
    VK_FORMAT_ASTC_10x10_SRGB_BLOCK
    VK_FORMAT_ASTC_12x10_UNORM_BLOCK
    VK_FORMAT_ASTC_12x10_SRGB_BLOCK
    VK_FORMAT_ASTC_12x12_UNORM_BLOCK
    VK_FORMAT_ASTC_12x12_SRGB_BLOCK
    VK_FORMAT_G8B8G8R8_422_UNORM
    VK_FORMAT_B8G8R8G8_422_UNORM
    VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM
    VK_FORMAT_G8_B8R8_2PLANE_420_UNORM
    VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM
    VK_FORMAT_G8_B8R8_2PLANE_422_UNORM
    VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM
    VK_FORMAT_R10X6_UNORM_PACK16
    VK_FORMAT_R10X6G10X6_UNORM_2PACK16
    VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16
    VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16
    VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16
    VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16
    VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16
    VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16
    VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16
    VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16
    VK_FORMAT_R12X4_UNORM_PACK16
    VK_FORMAT_R12X4G12X4_UNORM_2PACK16
    VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16
    VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16
    VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16
    VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16
    VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16
    VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16
    VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16
    VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16
    VK_FORMAT_G16B16G16R16_422_UNORM
    VK_FORMAT_B16G16R16G16_422_UNORM
    VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM
    VK_FORMAT_G16_B16R16_2PLANE_420_UNORM
    VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM
    VK_FORMAT_G16_B16R16_2PLANE_422_UNORM
    VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM
    VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG
    VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG
    VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG
    VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG
    VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG
    VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG
    VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG
    VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG
    ;; VK_FORMAT_G8B8G8R8_422_UNORM_KHR
    ;; VK_FORMAT_B8G8R8G8_422_UNORM_KHR
    ;; VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR
    ;; VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR
    ;; VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR
    ;; VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR
    ;; VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR
    ;; VK_FORMAT_R10X6_UNORM_PACK16_KHR
    ;; VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR
    ;; VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR
    ;; VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR
    ;; VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR
    ;; VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR
    ;; VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR
    ;; VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR
    ;; VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR
    ;; VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR
    ;; VK_FORMAT_R12X4_UNORM_PACK16_KHR
    ;; VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR
    ;; VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR
    ;; VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR
    ;; VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR
    ;; VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR
    ;; VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR
    ;; VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR
    ;; VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR
    ;; VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR
    ;; VK_FORMAT_G16B16G16R16_422_UNORM_KHR
    ;; VK_FORMAT_B16G16R16G16_422_UNORM_KHR
    ;; VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR
    ;; VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR
    ;; VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR
    ;; VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR
    ;; VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR
    ))

 (define-cenum <vk-imatge-type> "VkImageType"
   (VK_IMAGE_TYPE_1D
    VK_IMAGE_TYPE_2D
    VK_IMAGE_TYPE_3D
    ))

 (define-cenum <vk-image-tiling> "VkImageTiling"
   (VK_IMAGE_TILING_OPTIMAL
    VK_IMAGE_TILING_LINEAR
    ))

 (define-cenum <vk-physical-device-type> "VkPhysicalDeviceType"
   (VK_PHYSICAL_DEVICE_TYPE_OTHER
    VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
    VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
    VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU
    VK_PHYSICAL_DEVICE_TYPE_CPU
    ))

 (define-cenum <vk-query-type> "VkQueryType"
   (VK_QUERY_TYPE_OCCLUSION
    VK_QUERY_TYPE_PIPELINE_STATISTICS
    VK_QUERY_TYPE_TIMESTAMP
    ))

 (define-cenum <vk-sharing-mode> "VkSharingMode"
   (VK_SHARING_MODE_EXCLUSIVE
    VK_SHARING_MODE_CONCURRENT
    ))

 (define-cenum <vk-image-layout> "VkImageLayout"
   (VK_IMAGE_LAYOUT_UNDEFINED
    VK_IMAGE_LAYOUT_GENERAL
    VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL
    VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL
    VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
    VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL
    VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL
    VK_IMAGE_LAYOUT_PREINITIALIZED
    VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL
    VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL
    VK_IMAGE_LAYOUT_PRESENT_SRC_KHR
    VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR
    VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR
    VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR
    ))

 (define-cenum <vk-image-view-type> "VkImageViewType"
   (VK_IMAGE_VIEW_TYPE_1D
    VK_IMAGE_VIEW_TYPE_2D
    VK_IMAGE_VIEW_TYPE_3D
    VK_IMAGE_VIEW_TYPE_CUBE
    VK_IMAGE_VIEW_TYPE_1D_ARRAY
    VK_IMAGE_VIEW_TYPE_2D_ARRAY
    VK_IMAGE_VIEW_TYPE_CUBE_ARRAY
    ))

 (define-cenum <vk-component-swizzle> "VkComponentSwizzle"
   (VK_COMPONENT_SWIZZLE_IDENTITY
    VK_COMPONENT_SWIZZLE_ZERO
    VK_COMPONENT_SWIZZLE_ONE
    VK_COMPONENT_SWIZZLE_R
    VK_COMPONENT_SWIZZLE_G
    VK_COMPONENT_SWIZZLE_B
    VK_COMPONENT_SWIZZLE_A
    ))

 (define-cenum <vk-vertex-input-rate> "VkVertexInputRate"
   (VK_VERTEX_INPUT_RATE_VERTEX
    VK_VERTEX_INPUT_RATE_INSTANCE
    ))

 (define-cenum <vk-primitive-topology> "VkPrimitiveTopology"
   (VK_PRIMITIVE_TOPOLOGY_POINT_LIST
    VK_PRIMITIVE_TOPOLOGY_LINE_LIST
    VK_PRIMITIVE_TOPOLOGY_LINE_STRIP
    VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST
    VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP
    VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN
    VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY
    VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY
    VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY
    VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY
    VK_PRIMITIVE_TOPOLOGY_PATCH_LIST
    ))

 (define-cenum <vk-polygon-mode> "VkPolygonMode"
   (VK_POLYGON_MODE_FILL
    VK_POLYGON_MODE_LINE
    VK_POLYGON_MODE_POINT
    VK_POLYGON_MODE_FILL_RECTANGLE_NV
    ))

 (define-cenum <vk-front-face> "VkFrontFace"
   (VK_FRONT_FACE_COUNTER_CLOCKWISE
    VK_FRONT_FACE_CLOCKWISE
    ))

 (define-cenum <vk-compare-op> "VkCompareOp"
   (VK_COMPARE_OP_NEVER
    VK_COMPARE_OP_LESS
    VK_COMPARE_OP_EQUAL
    VK_COMPARE_OP_LESS_OR_EQUAL
    VK_COMPARE_OP_GREATER
    VK_COMPARE_OP_NOT_EQUAL
    VK_COMPARE_OP_GREATER_OR_EQUAL
    VK_COMPARE_OP_ALWAYS
    ))

 (define-cenum <vk-stencil-op> "VkStencilOp"
   (VK_STENCIL_OP_KEEP
    VK_STENCIL_OP_ZERO
    VK_STENCIL_OP_REPLACE
    VK_STENCIL_OP_INCREMENT_AND_CLAMP
    VK_STENCIL_OP_DECREMENT_AND_CLAMP
    VK_STENCIL_OP_INVERT
    VK_STENCIL_OP_INCREMENT_AND_WRAP
    VK_STENCIL_OP_DECREMENT_AND_WRAP
    ))

 (define-cenum <vk-logic-op> "VkLogicOp"
   (VK_LOGIC_OP_CLEAR
    VK_LOGIC_OP_AND
    VK_LOGIC_OP_AND_REVERSE
    VK_LOGIC_OP_COPY
    VK_LOGIC_OP_AND_INVERTED
    VK_LOGIC_OP_NO_OP
    VK_LOGIC_OP_XOR
    VK_LOGIC_OP_OR
    VK_LOGIC_OP_NOR
    VK_LOGIC_OP_EQUIVALENT
    VK_LOGIC_OP_INVERT
    VK_LOGIC_OP_OR_REVERSE
    VK_LOGIC_OP_COPY_INVERTED
    VK_LOGIC_OP_OR_INVERTED
    VK_LOGIC_OP_NAND
    VK_LOGIC_OP_SET
    ))

 (define-cenum <vk-blend-factor> "VkBlendFactor"
   (VK_BLEND_FACTOR_ZERO
    VK_BLEND_FACTOR_ONE
    VK_BLEND_FACTOR_SRC_COLOR
    VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR
    VK_BLEND_FACTOR_DST_COLOR
    VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR
    VK_BLEND_FACTOR_SRC_ALPHA
    VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA
    VK_BLEND_FACTOR_DST_ALPHA
    VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA
    VK_BLEND_FACTOR_CONSTANT_COLOR
    VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR
    VK_BLEND_FACTOR_CONSTANT_ALPHA
    VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA
    VK_BLEND_FACTOR_SRC_ALPHA_SATURATE
    VK_BLEND_FACTOR_SRC1_COLOR
    VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR
    VK_BLEND_FACTOR_SRC1_ALPHA
    VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA
    ))

 (define-cenum <vk-blend-op> "VkBlendOp"
   (VK_BLEND_OP_ADD
    VK_BLEND_OP_SUBTRACT
    VK_BLEND_OP_REVERSE_SUBTRACT
    VK_BLEND_OP_MIN
    VK_BLEND_OP_MAX
    ;; VK_BLEND_OP_ZERO_EXT
    ;; VK_BLEND_OP_SRC_EXT
    ;; VK_BLEND_OP_DST_EXT
    ;; VK_BLEND_OP_SRC_OVER_EXT
    ;; VK_BLEND_OP_DST_OVER_EXT
    ;; VK_BLEND_OP_SRC_IN_EXT
    ;; VK_BLEND_OP_DST_IN_EXT
    ;; VK_BLEND_OP_SRC_OUT_EXT
    ;; VK_BLEND_OP_DST_OUT_EXT
    ;; VK_BLEND_OP_SRC_ATOP_EXT
    ;; VK_BLEND_OP_DST_ATOP_EXT
    ;; VK_BLEND_OP_XOR_EXT
    ;; VK_BLEND_OP_MULTIPLY_EXT
    ;; VK_BLEND_OP_SCREEN_EXT
    ;; VK_BLEND_OP_OVERLAY_EXT
    ;; VK_BLEND_OP_DARKEN_EXT
    ;; VK_BLEND_OP_LIGHTEN_EXT
    ;; VK_BLEND_OP_COLORDODGE_EXT
    ;; VK_BLEND_OP_COLORBURN_EXT
    ;; VK_BLEND_OP_HARDLIGHT_EXT
    ;; VK_BLEND_OP_SOFTLIGHT_EXT
    ;; VK_BLEND_OP_DIFFERENCE_EXT
    ;; VK_BLEND_OP_EXCLUSION_EXT
    ;; VK_BLEND_OP_INVERT_EXT
    ;; VK_BLEND_OP_INVERT_RGB_EXT
    ;; VK_BLEND_OP_LINEARDODGE_EXT
    ;; VK_BLEND_OP_LINEARBURN_EXT
    ;; VK_BLEND_OP_VIVIDLIGHT_EXT
    ;; VK_BLEND_OP_LINEARLIGHT_EXT
    ;; VK_BLEND_OP_PINLIGHT_EXT
    ;; VK_BLEND_OP_HARDMIX_EXT
    ;; VK_BLEND_OP_HSL_HUE_EXT
    ;; VK_BLEND_OP_HSL_SATURATION_EXT
    ;; VK_BLEND_OP_HSL_COLOR_EXT
    ;; VK_BLEND_OP_HSL_LUMINOSITY_EXT
    ;; VK_BLEND_OP_PLUS_EXT
    ;; VK_BLEND_OP_PLUS_CLAMPED_EXT
    ;; VK_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT
    ;; VK_BLEND_OP_PLUS_DARKER_EXT
    ;; VK_BLEND_OP_MINUS_EXT
    ;; VK_BLEND_OP_MINUS_CLAMPED_EXT
    ;; VK_BLEND_OP_CONTRAST_EXT
    ;; VK_BLEND_OP_INVERT_OVG_EXT
    ;; VK_BLEND_OP_RED_EXT
    ;; VK_BLEND_OP_GREEN_EXT
    ;; VK_BLEND_OP_BLUE_EXT
    ))

 (define-cenum <vk-dynamic-state> "VkDynamicState"
   (VK_DYNAMIC_STATE_VIEWPORT
    VK_DYNAMIC_STATE_SCISSOR
    VK_DYNAMIC_STATE_LINE_WIDTH
    VK_DYNAMIC_STATE_DEPTH_BIAS
    VK_DYNAMIC_STATE_BLEND_CONSTANTS
    VK_DYNAMIC_STATE_DEPTH_BOUNDS
    VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK
    VK_DYNAMIC_STATE_STENCIL_WRITE_MASK
    VK_DYNAMIC_STATE_STENCIL_REFERENCE
    ;; VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV
    ;; VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT
    ;; VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT
    ))

 (define-cenum <vk-filter> "VkFilter"
   (VK_FILTER_NEAREST
    VK_FILTER_LINEAR
    VK_FILTER_CUBIC_IMG
    ))

 (define-cenum <vk-sampler-mipmap-mode> "VkSamplerMipmapMode"
   (VK_SAMPLER_MIPMAP_MODE_NEAREST
    VK_SAMPLER_MIPMAP_MODE_LINEAR
    ))

 (define-cenum <vk-sampler-address-mode> "VkSamplerAddressMode"
   (VK_SAMPLER_ADDRESS_MODE_REPEAT
    VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER
    VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE
    ))

 (define-cenum <vk-border-color> "VkBorderColor"
   (VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK
    VK_BORDER_COLOR_INT_TRANSPARENT_BLACK
    VK_BORDER_COLOR_FLOAT_OPAQUE_BLACK
    VK_BORDER_COLOR_INT_OPAQUE_BLACK
    VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE
    VK_BORDER_COLOR_INT_OPAQUE_WHITE
    ))

 (define-cenum <vk-descriptor-type> "VkDescriptorType"
   (VK_DESCRIPTOR_TYPE_SAMPLER
    VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER
    VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE
    VK_DESCRIPTOR_TYPE_STORAGE_IMAGE
    VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER
    VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER
    VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER
    VK_DESCRIPTOR_TYPE_STORAGE_BUFFER
    VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC
    VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC
    VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT
    ))

 (define-cenum <vk-attachment-load-op> "VkAttachmentLoadOp"
   (VK_ATTACHMENT_LOAD_OP_LOAD
    VK_ATTACHMENT_LOAD_OP_CLEAR
    VK_ATTACHMENT_LOAD_OP_DONT_CARE
    ))

 (define-cenum <vk-attachment-store-op> "VkAttachmentStoreOp"
   (VK_ATTACHMENT_STORE_OP_STORE
    VK_ATTACHMENT_STORE_OP_DONT_CARE
    ))

 (define-cenum <vk-pipeline-bind-point> "VkPipelineBindPoint"
   (VK_PIPELINE_BIND_POINT_GRAPHICS
    VK_PIPELINE_BIND_POINT_COMPUTE
    ))

 (define-cenum <vk-command-buffer-level> "VkCommandBufferLevel"
   (VK_COMMAND_BUFFER_LEVEL_PRIMARY
    VK_COMMAND_BUFFER_LEVEL_SECONDARY
    ))

 (define-cenum <vk-index-type> "VkIndexType"
   (VK_INDEX_TYPE_UINT16
    VK_INDEX_TYPE_UINT32
    ))

 (define-cenum <vk-subpass-contents> "VkSubpassContents"
   (VK_SUBPASS_CONTENTS_INLINE
    VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS
    ))

 (define-cenum <vk-object-type> "VkObjectType"
   (VK_OBJECT_TYPE_UNKNOWN
    VK_OBJECT_TYPE_INSTANCE
    VK_OBJECT_TYPE_PHYSICAL_DEVICE
    VK_OBJECT_TYPE_DEVICE
    VK_OBJECT_TYPE_QUEUE
    VK_OBJECT_TYPE_SEMAPHORE
    VK_OBJECT_TYPE_COMMAND_BUFFER
    VK_OBJECT_TYPE_FENCE
    VK_OBJECT_TYPE_DEVICE_MEMORY
    VK_OBJECT_TYPE_BUFFER
    VK_OBJECT_TYPE_IMAGE
    VK_OBJECT_TYPE_EVENT
    VK_OBJECT_TYPE_QUERY_POOL
    VK_OBJECT_TYPE_BUFFER_VIEW
    VK_OBJECT_TYPE_IMAGE_VIEW
    VK_OBJECT_TYPE_SHADER_MODULE
    VK_OBJECT_TYPE_PIPELINE_CACHE
    VK_OBJECT_TYPE_PIPELINE_LAYOUT
    VK_OBJECT_TYPE_RENDER_PASS
    VK_OBJECT_TYPE_PIPELINE
    VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT
    VK_OBJECT_TYPE_SAMPLER
    VK_OBJECT_TYPE_DESCRIPTOR_POOL
    VK_OBJECT_TYPE_DESCRIPTOR_SET
    VK_OBJECT_TYPE_FRAMEBUFFER
    VK_OBJECT_TYPE_COMMAND_POOL
    VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION
    VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE
    ;; VK_OBJECT_TYPE_SURFACE_KHR
    ;; VK_OBJECT_TYPE_SWAPCHAIN_KHR
    ;; VK_OBJECT_TYPE_DISPLAY_KHR
    ;; VK_OBJECT_TYPE_DISPLAY_MODE_KHR
    ;; VK_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT
    ;; VK_OBJECT_TYPE_OBJECT_TABLE_NVX
    ;; VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVX
    ;; VK_OBJECT_TYPE_DEBUG_UTILS_MESSENGER_EXT
    ;; VK_OBJECT_TYPE_VALIDATION_CACHE_EXT
    ;; VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_KHR
    ;; VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR
    ))

 (define-cenum <vk-format-feature-flag-bits> "VkFormatFeatureFlagBits"
   (VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT
    VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT
    VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT
    VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT
    VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT
    VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT
    VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT
    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT
    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT
    VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT
    VK_FORMAT_FEATURE_BLIT_SRC_BIT
    VK_FORMAT_FEATURE_BLIT_DST_BIT
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT
    VK_FORMAT_FEATURE_TRANSFER_SRC_BIT
    VK_FORMAT_FEATURE_TRANSFER_DST_BIT
    VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT
    VK_FORMAT_FEATURE_DISJOINT_BIT
    VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG
    ;; VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT
    ;; VK_FORMAT_FEATURE_TRANSFER_SRC_BIT_KHR
    ;; VK_FORMAT_FEATURE_TRANSFER_DST_BIT_KHR
    ;; VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR
    ;; VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR
    ;; VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR
    ;; VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR
    ;; VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR
    ;; VK_FORMAT_FEATURE_DISJOINT_BIT_KHR
    ;; VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR
    ))

 (define-cenum <vk-image-create-flag-bits> "VkImageCreateFlagBits"
   (VK_IMAGE_CREATE_SPARSE_BINDING_BIT
    VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT
    VK_IMAGE_CREATE_SPARSE_ALIASED_BIT
    VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT
    VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT
    VK_IMAGE_CREATE_ALIAS_BIT
    VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT
    VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT
    VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT
    VK_IMAGE_CREATE_EXTENDED_USAGE_BIT
    VK_IMAGE_CREATE_PROTECTED_BIT
    VK_IMAGE_CREATE_DISJOINT_BIT
    ;; VK_IMAGE_CREATE_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_BIT_EXT
    ;; VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR
    ;; VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT_KHR
    ;; VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT_KHR
    ;; VK_IMAGE_CREATE_EXTENDED_USAGE_BIT_KHR
    ;; VK_IMAGE_CREATE_DISJOINT_BIT_KHR
    ;; VK_IMAGE_CREATE_ALIAS_BIT_KHR
    ))

 (define-cenum <vk-sample-count-flag-bits> "VkSampleCountFlagBits"
   (VK_SAMPLE_COUNT_1_BIT
    VK_SAMPLE_COUNT_2_BIT
    VK_SAMPLE_COUNT_4_BIT
    VK_SAMPLE_COUNT_8_BIT
    VK_SAMPLE_COUNT_16_BIT
    VK_SAMPLE_COUNT_32_BIT
    VK_SAMPLE_COUNT_64_BIT
    ))

 (define-cenum <vk-queue-flag-bits> "VkQueueFlagBits"
   (VK_QUEUE_GRAPHICS_BIT
    VK_QUEUE_COMPUTE_BIT
    VK_QUEUE_TRANSFER_BIT
    VK_QUEUE_SPARSE_BINDING_BIT
    VK_QUEUE_PROTECTED_BIT
    ))

 (define-cenum <vk-memory-property-flag-bits> "VkMemoryPropertyFlagBits"
   (VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT
    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT
    VK_MEMORY_PROPERTY_HOST_COHERENT_BIT
    VK_MEMORY_PROPERTY_HOST_CACHED_BIT
    VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT
    VK_MEMORY_PROPERTY_PROTECTED_BIT
    ))

 (define-cenum <vk-memory-heap-flag-bits> "VkMemoryHeapFlagBits"
   (VK_MEMORY_HEAP_DEVICE_LOCAL_BIT
    VK_MEMORY_HEAP_MULTI_INSTANCE_BIT
    ;;VK_MEMORY_HEAP_MULTI_INSTANCE_BIT_KHR
    ))

 (define-cenum <vk-device-queue-create-flag-bits> "VkDeviceQueueCreateFlagBits"
   (VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT
    ))

 (define-cenum <vk-pipeline-stage-flag-bits> "VkPipelineStageFlagBits"
   (VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT
    VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT
    VK_PIPELINE_STAGE_VERTEX_INPUT_BIT
    VK_PIPELINE_STAGE_VERTEX_SHADER_BIT
    VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT
    VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT
    VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT
    VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT
    VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT
    VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT
    VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT
    VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT
    VK_PIPELINE_STAGE_TRANSFER_BIT
    VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT
    VK_PIPELINE_STAGE_HOST_BIT
    VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT
    VK_PIPELINE_STAGE_ALL_COMMANDS_BIT
    ;;VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX
    ))

 (define-cenum <vk-image-aspect-flag-bits> "VkImageAspectFlagBits"
   (VK_IMAGE_ASPECT_COLOR_BIT
    VK_IMAGE_ASPECT_DEPTH_BIT
    VK_IMAGE_ASPECT_STENCIL_BIT
    VK_IMAGE_ASPECT_METADATA_BIT
    VK_IMAGE_ASPECT_PLANE_0_BIT
    VK_IMAGE_ASPECT_PLANE_1_BIT
    VK_IMAGE_ASPECT_PLANE_2_BIT
    ;; VK_IMAGE_ASPECT_PLANE_0_BIT_KHR
    ;; VK_IMAGE_ASPECT_PLANE_1_BIT_KHR
    ;; VK_IMAGE_ASPECT_PLANE_2_BIT_KHR
    ))

 (define-cenum <vk-sparse-image-format-flag-bits> "VkSparseImageFormatFlagBits"
   (VK_SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT
    VK_SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT
    VK_SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT
    ))

 (define-cenum <vk-sparse-memory-bind-flag-bits> "VkSparseMemoryBindFlagBits"
   (VK_SPARSE_MEMORY_BIND_METADATA_BIT
    ))

 (define-cenum <vk-fence-create-flag-bits> "VkFenceCreateFlagBits"
   (VK_FENCE_CREATE_SIGNALED_BIT
    ))

 (define-cenum <vk-query-pipeline-statistic-flag-bits>
   "VkQueryPipelineStatisticFlagBits"
   (VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT
    VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT
    VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT
    VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT
    VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT
    VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT
    VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT
    VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT
    VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT
    VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT
    VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT
    ))

 (define-cenum <vk-query-result-flag-bits> "VkQueryResultFlagBits"
   (VK_QUERY_RESULT_64_BIT
    VK_QUERY_RESULT_WAIT_BIT
    VK_QUERY_RESULT_WITH_AVAILABILITY_BIT
    VK_QUERY_RESULT_PARTIAL_BIT
    ))

 (define-cenum <vk-buffer-create-flag-bits> "VkBufferCreateFlagBits"
   (VK_BUFFER_CREATE_SPARSE_BINDING_BIT
    VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT
    VK_BUFFER_CREATE_SPARSE_ALIASED_BIT
    VK_BUFFER_CREATE_PROTECTED_BIT
    ))

 (define-cenum <vk-buffer-usage-flag-bits> "VkBufferUsageFlagBits"
   (VK_BUFFER_USAGE_TRANSFER_SRC_BIT
    VK_BUFFER_USAGE_TRANSFER_DST_BIT
    VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT
    VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT
    VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT
    VK_BUFFER_USAGE_STORAGE_BUFFER_BIT
    VK_BUFFER_USAGE_INDEX_BUFFER_BIT
    VK_BUFFER_USAGE_VERTEX_BUFFER_BIT
    VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT
    ))

 (define-cenum <vk-pipeline-create-flag-bits> "VkPipelineCreateFlagBits"
   (VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT
    VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT
    VK_PIPELINE_CREATE_DERIVATIVE_BIT
    VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT
    VK_PIPELINE_CREATE_DISPATCH_BASE
    ;; VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR
    ;; VK_PIPELINE_CREATE_DISPATCH_BASE_KHR
    ))

 (define-cenum <vk-shader-stage-flag-bits> "VkShaderStageFlagBits"
   (VK_SHADER_STAGE_VERTEX_BIT
    VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT
    VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT
    VK_SHADER_STAGE_GEOMETRY_BIT
    VK_SHADER_STAGE_FRAGMENT_BIT
    VK_SHADER_STAGE_COMPUTE_BIT
    VK_SHADER_STAGE_ALL_GRAPHICS
    VK_SHADER_STAGE_ALL
    ))

 (define-cenum <vk-cull-mode-flag-bits> "VkCullModeFlagBits"
   (VK_CULL_MODE_NONE
    VK_CULL_MODE_FRONT_BIT
    VK_CULL_MODE_BACK_BIT
    VK_CULL_MODE_FRONT_AND_BACK
    ))

 (define-cenum <vk-color-component-flag-bits> "VkColorComponentFlagBits"
   (VK_COLOR_COMPONENT_R_BIT
    VK_COLOR_COMPONENT_G_BIT
    VK_COLOR_COMPONENT_B_BIT
    VK_COLOR_COMPONENT_A_BIT
    ))

 (define-cenum <vk-descriptor-set-layout-create-flag-bits>
   "VkDescriptorSetLayoutCreateFlagBits"
   (VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR
    ))

 (define-cenum <vk-descriptor-pool-create-flag-bits>
   "VkDescriptorPoolCreateFlagBits"
   (VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT
    ))

 (define-cenum <vk-attachment-description-flag-bits>
   "VkAttachmentDescriptionFlagBits"
   (VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT
    ))

 (define-cenum <vk-subpass-description-flag-bits> "VkSubpassDescriptionFlagBits"
   (VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX
    VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX
    ))

 (define-cenum <vk-access-flag-bits> "VkAccessFlagBits"
   (VK_ACCESS_INDIRECT_COMMAND_READ_BIT
    VK_ACCESS_INDEX_READ_BIT
    VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT
    VK_ACCESS_UNIFORM_READ_BIT
    VK_ACCESS_INPUT_ATTACHMENT_READ_BIT
    VK_ACCESS_SHADER_READ_BIT
    VK_ACCESS_SHADER_WRITE_BIT
    VK_ACCESS_COLOR_ATTACHMENT_READ_BIT
    VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT
    VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT
    VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT
    VK_ACCESS_TRANSFER_READ_BIT
    VK_ACCESS_TRANSFER_WRITE_BIT
    VK_ACCESS_HOST_READ_BIT
    VK_ACCESS_HOST_WRITE_BIT
    VK_ACCESS_MEMORY_READ_BIT
    VK_ACCESS_MEMORY_WRITE_BIT
    ;; VK_ACCESS_COMMAND_PROCESS_READ_BIT_NVX
    ;; VK_ACCESS_COMMAND_PROCESS_WRITE_BIT_NVX
    ;; VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT
    ))

 (define-cenum <vk-dependency-flag-bits> "VkDependencyFlagBits"
   (VK_DEPENDENCY_BY_REGION_BIT
    VK_DEPENDENCY_DEVICE_GROUP_BIT
    VK_DEPENDENCY_VIEW_LOCAL_BIT
    ;; VK_DEPENDENCY_VIEW_LOCAL_BIT_KHR
    ;; VK_DEPENDENCY_DEVICE_GROUP_BIT_KHR
    ))

 (define-cenum <vk-command-pool-create-flag-bits> "VkCommandPoolCreateFlagBits"
   (VK_COMMAND_POOL_CREATE_TRANSIENT_BIT
    VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT
    VK_COMMAND_POOL_CREATE_PROTECTED_BIT
    ))

 (define-cenum <vk-command-pool-reset-flag-bits> "VkCommandPoolResetFlagBits"
   (VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT
    ))

 (define-cenum <vk-command-buffer-usage-flag-bits>
   "VkCommandBufferUsageFlagBits"
   (VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT
    VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT
    VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT
    ))

 (define-cenum <vk-query-control-flag-bits> "VkQueryControlFlagBits"
   (VK_QUERY_CONTROL_PRECISE_BIT
    ))

 (define-cenum <vk-command-buffer-reset-flag-bits>
   "VkCommandBufferResetFlagBits"
   (VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT
    ))

 (define-cenum <vk-stencil-face-flag-bits> "VkStencilFaceFlagBits"
   (VK_STENCIL_FACE_FRONT_BIT
    VK_STENCIL_FACE_BACK_BIT
    VK_STENCIL_FRONT_AND_BACK
    ))

 (define-type <vk-bool32> "VkBool32" #f
   "SCM_INTEGERP" "Scm_GetIntegerU32" "Scm_MakeIntegerU")

 (define-type <vk-flags> "VkFlags" #f
   "SCM_INTP" "SCM_INT_VALUE" "SCM_MAKE_INT")

 (define-type <vk-device-size> "VkDeviceSize" #f
   "SCM_INTEGERP" "Scm_GetIntegerU64" "Scm_MakeIntegerU64")

 (define-cstruct <vk-application-info> "VkApplicationInfo"
   (sType::<vk-structure-type> "=VK_STRUCTURE_TYPE_APPLICATION_INFO"
    pNext::<vk-void*> "=NULL"
    pApplicationName::<const-cstring>
    applicationVersion::<uint32>
    pEngineName::<const-cstring>
    engineVersion::<uint32>
    apiVersion::<uint32>))

 (define-cstruct <vk-instance-create-info> "VkInstanceCreateInfo"
   (sType::<vk-structure-type> "=VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO"
    pNext::<vk-void*> "=NULL"
    flags::<vk-flags>
    pApplicationInfo::<vk-application-info>
    enabledLayerCount::<uint32> "=0"
    ppEnabledLayerNames::(.array* <const-cstring>) "ppEnabledLayerNames[enabledLayerCount]"
    enabledExtensionCount::<uint32> "=0"
    ppEnabledExtensionNames::(.array* <const-cstring>) "ppEnabledExtensionNames[enabledExtensionCount]"))

 (define-cstruct <vk-physical-device-features> "VkPhysicalDeviceFeatures"
   (robustBufferAccess::<boolean>
    fullDrawIndexUint32::<boolean>
    imageCubeArray::<boolean>
    independentBlend::<boolean>
    geometryShader::<boolean>
    tessellationShader::<boolean>
    sampleRateShading::<boolean>
    dualSrcBlend::<boolean>
    logicOp::<boolean>
    multiDrawIndirect::<boolean>
    drawIndirectFirstInstance::<boolean>
    depthClamp::<boolean>
    depthBiasClamp::<boolean>
    fillModeNonSolid::<boolean>
    depthBounds::<boolean>
    wideLines::<boolean>
    largePoints::<boolean>
    alphaToOne::<boolean>
    multiViewport::<boolean>
    samplerAnisotropy::<boolean>
    textureCompressionETC2::<boolean>
    textureCompressionASTC_LDR::<boolean>
    textureCompressionBC::<boolean>
    occlusionQueryPrecise::<boolean>
    pipelineStatisticsQuery::<boolean>
    vertexPipelineStoresAndAtomics::<boolean>
    fragmentStoresAndAtomics::<boolean>
    shaderTessellationAndGeometryPointSize::<boolean>
    shaderImageGatherExtended::<boolean>
    shaderStorageImageExtendedFormats::<boolean>
    shaderStorageImageMultisample::<boolean>
    shaderStorageImageReadWithoutFormat::<boolean>
    shaderStorageImageWriteWithoutFormat::<boolean>
    shaderUniformBufferArrayDynamicIndexing::<boolean>
    shaderSampledImageArrayDynamicIndexing::<boolean>
    shaderStorageBufferArrayDynamicIndexing::<boolean>
    shaderStorageImageArrayDynamicIndexing::<boolean>
    shaderClipDistance::<boolean>
    shaderCullDistance::<boolean>
    shaderFloat64::<boolean>
    shaderInt64::<boolean>
    shaderInt16::<boolean>
    shaderResourceResidency::<boolean>
    shaderResourceMinLod::<boolean>
    sparseBinding::<boolean>
    sparseResidencyBuffer::<boolean>
    sparseResidencyImage2D::<boolean>
    sparseResidencyImage3D::<boolean>
    sparseResidency2Samples::<boolean>
    sparseResidency4Samples::<boolean>
    sparseResidency8Samples::<boolean>
    sparseResidency16Samples::<boolean>
    sparseResidencyAliased::<boolean>
    variableMultisampleRate::<boolean>
    inheritedQueries::<boolean>))

 (define-cstruct <vk-format-properties> "VkFormatProperties"
   (linearTilingFeatures::<vk-flags>
    optimalTilingFeatures::<vk-flags>
    bufferFeatures::<vk-flags>))

 (define-cstruct <vk-extent-3d> "VkExtent3D"
   (width::<uint32>
    height::<uint32>
    depth::<uint32>))

 (define-cstruct <vk-image-format-properties> "VkImageFormatProperties"
   (maxExtent::&<vk-extent-3d>
    maxMipLevels::<uint32>
    maxArrayLayers::<uint32>
    sampleCounts::<vk-flags>
    maxResourceSize::<vk-device-size>))

 (define-cstruct <vk-physical-device-limits> "VkPhysicalDeviceLimits"
   (maxImageDimension1D::<uint32>
    maxImageDimension2D::<uint32>
    maxImageDimension3D::<uint32>
    maxImageDimensionCube::<uint32>
    maxImageArrayLayers::<uint32>
    maxTexelBufferElements::<uint32>
    maxUniformBufferRange::<uint32>
    maxStorageBufferRange::<uint32>
    maxPushConstantsSize::<uint32>
    maxMemoryAllocationCount::<uint32>
    maxSamplerAllocationCount::<uint32>
    bufferImageGranularity::<vk-device-size>
    sparseAddressSpaceSize::<vk-device-size>
    maxBoundDescriptorSets::<uint32>
    maxPerStageDescriptorSamplers::<uint32>
    maxPerStageDescriptorUniformBuffers::<uint32>
    maxPerStageDescriptorStorageBuffers::<uint32>
    maxPerStageDescriptorSampledImages::<uint32>
    maxPerStageDescriptorStorageImages::<uint32>
    maxPerStageDescriptorInputAttachments::<uint32>
    maxPerStageResources::<uint32>
    maxDescriptorSetSamplers::<uint32>
    maxDescriptorSetUniformBuffers::<uint32>
    maxDescriptorSetUniformBuffersDynamic::<uint32>
    maxDescriptorSetStorageBuffers::<uint32>
    maxDescriptorSetStorageBuffersDynamic::<uint32>
    maxDescriptorSetSampledImages::<uint32>
    maxDescriptorSetStorageImages::<uint32>
    maxDescriptorSetInputAttachments::<uint32>
    maxVertexInputAttributes::<uint32>
    maxVertexInputBindings::<uint32>
    maxVertexInputAttributeOffset::<uint32>
    maxVertexInputBindingStride::<uint32>
    maxVertexOutputComponents::<uint32>
    maxTessellationGenerationLevel::<uint32>
    maxTessellationPatchSize::<uint32>
    maxTessellationControlPerVertexInputComponents::<uint32>
    maxTessellationControlPerVertexOutputComponents::<uint32>
    maxTessellationControlPerPatchOutputComponents::<uint32>
    maxTessellationControlTotalOutputComponents::<uint32>
    maxTessellationEvaluationInputComponents::<uint32>
    maxTessellationEvaluationOutputComponents::<uint32>
    maxGeometryShaderInvocations::<uint32>
    maxGeometryInputComponents::<uint32>
    maxGeometryOutputComponents::<uint32>
    maxGeometryOutputVertices::<uint32>
    maxGeometryTotalOutputComponents::<uint32>
    maxFragmentInputComponents::<uint32>
    maxFragmentOutputAttachments::<uint32>
    maxFragmentDualSrcAttachments::<uint32>
    maxFragmentCombinedOutputResources::<uint32>
    maxComputeSharedMemorySize::<uint32>
    maxComputeWorkGroupCount::(.array <uint32>) "[3]"
    maxComputeWorkGroupInvocations::<uint32>
    maxComputeWorkGroupSize::(.array <uint32>) "[3]"
    subPixelPrecisionBits::<uint32>
    subTexelPrecisionBits::<uint32>
    mipmapPrecisionBits::<uint32>
    maxDrawIndexedIndexValue::<uint32>
    maxDrawIndirectCount::<uint32>
    maxSamplerLodBias::<float>
    maxSamplerAnisotropy::<float>
    maxViewports::<uint32>
    maxViewportDimensions::(.array <uint32>) "[2]"
    viewportBoundsRange::(.array <float>) "[2]"
    viewportSubPixelBits::<uint32>
    minMemoryMapAlignment::<ulong>     ;; actually, size_t
    minTexelBufferOffsetAlignment::<vk-device-size>
    minUniformBufferOffsetAlignment::<vk-device-size>
    minStorageBufferOffsetAlignment::<vk-device-size>
    minTexelOffset::<int32>
    maxTexelOffset::<uint32>
    minTexelGatherOffset::<int32>
    maxTexelGatherOffset::<uint32>
    minInterpolationOffset::<float>
    maxInterpolationOffset::<float>
    subPixelInterpolationOffsetBits::<uint32>
    maxFramebufferWidth::<uint32>
    maxFramebufferHeight::<uint32>
    maxFramebufferLayers::<uint32>
    framebufferColorSampleCounts::<vk-flags>
    framebufferDepthSampleCounts::<vk-flags>
    framebufferStencilSampleCounts::<vk-flags>
    framebufferNoAttachmentsSampleCounts::<vk-flags>
    maxColorAttachments::<uint32>
    sampledImageColorSampleCounts::<vk-flags>
    sampledImageIntegerSampleCounts::<vk-flags>
    sampledImageDepthSampleCounts::<vk-flags>
    sampledImageStencilSampleCounts::<vk-flags>
    storageImageSampleCounts::<vk-flags>
    maxSampleMaskWords::<uint32>
    timestampComputeAndGraphics::<vk-bool32>
    timestampPeriod::<float>
    maxClipDistances::<uint32>
    maxCullDistances::<uint32>
    maxCombinedClipAndCullDistances::<uint32>
    discreteQueuePriorities::<uint32>
    pointSizeRange::(.array <float>) "[2]"
    lineWidthRange::(.array <float>) "[2]"
    pointSizeGranularity::<float>
    lineWidthGranularity::<float>
    strictLines::<vk-bool32>
    standardSampleLocations::<vk-bool32>
    optimalBufferCopyOffsetAlignment::<vk-device-size>
    optimalBufferCopyRowPitchAlignment::<vk-device-size>
    nonCoherentAtomSize::<vk-device-size>))
 )
